### ISSUE TITLE
vulnerability in color-string module

### ISSUE THREAD

**Issue by GAP-dev** [Qix-/color-string#71]
hello!
i found vulnerability in color-string module.
where can i report this?

**Comment by Qix-** [comment]
Hi, please send to `github at josh dot junon dot me`.

**Comment by GAP-dev** [comment]
josh@junon.me
is correct?
or github@josh.junon.me
is correct?

**Comment by Qix-** [comment]
`github@` is correct, and I've edited your comment so that web scrapers don't try to spam me. Can I ask how you found the first email address?

**Comment by GAP-dev** [comment]
oh, sorry...
I checked your linked in, and I found your website.
so I guess through domain..!

**Comment by Qix-** [comment]
Hi, thank you for the responsible disclosure.

I don't consider redos vulnerabilities to be CVE-worthy as the surface area for any meaningful exploit is significantly low. I've had lots of issues with redos CVEs in the past (see @debug-js/debug issue tracker) and no longer consider these vulnerabilities. This is to reduce the abuse of CVE bounty programs and their collateral damage on the OSS community.

If the fix is trivial, or if you feel that a note should be added to the readme, a PR is welcome. Thanks!

**Comment by GAP-dev** [comment]
can i send one more mail with poc video and my opinion?

**Comment by Qix-** [comment]
Yes, sure. However I know exactly what ReDOS vulnerabilities look like. They're not exploited in the wild much at all unless this library is exposed in a way where unsanitized inputs are allowed, which is almost always a bad idea and usually not the case.

I appreciate that there are edge cases where this might be an issue but so many researchers have spammed me with duplicate ReDOS vulns just to bolster their own portfolio or to claim monetary bounties and have caused chaos on several repositories.

**Comment by GAP-dev** [comment]
<img width="559" alt="Screenshot 2023-10-17 at 3 22 54 PM" src="https://github.com/Qix-/color-string/assets/73922876/8036afad-a322-415b-8c47-6262bd6cf94a">

is it my problem..?

**Comment by Qix-** [comment]
No, apologies. Try again today please. The domain lapsed and google didn't notify me.

**Comment by GAP-dev** [comment]
Are you check my second mail?
![image](https://github.com/Qix-/color-string/assets/73922876/07c89a8d-17b8-4fe3-a286-3296e3da2f7c)

**Comment by Qix-** [comment]
Hi, I already responded that you're welcome to make a PR regarding the changes to the regexes to reduce their complexity.
